# Generated by Django 4.2.2 on 2023-06-30 10:40
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profile/Без_названия_3.jpeg",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
