# Generated by Django 4.2.2 on 2023-06-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0002_alter_profile_profile_pic_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="static/"),
        ),
    ]
