# Generated by Django 4.2.2 on 2023-07-25 13:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0002_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profile/defaul_user_image.png",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
