# Generated by Django 4.2.2 on 2023-07-11 18:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("пользователь", "USER"),
                    ("менеджер", "MANAGER"),
                    ("администратор", "ADMIN"),
                ],
                default="пользователь",
                max_length=15,
                verbose_name="Статус",
            ),
        ),
    ]
