# Generated by Django 4.2.2 on 2023-06-09 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_movie_actors_alter_movie_director_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("description", models.TextField(verbose_name="Описание")),
                ("url", models.SlugField(max_length=100, verbose_name="URL")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movie_of_category",
                to="movies.category",
                verbose_name="Категория",
            ),
        ),
    ]
