# Generated by Django 4.2.2 on 2023-07-06 19:56
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("publish", "Опубликовано")],
                default="draft",
                max_length=7,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="raiting",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Оценка",
            ),
        ),
    ]
