# Generated by Django 4.2.2 on 2023-07-08 21:51
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_movie_status_alter_raiting_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="movies.movie",
                verbose_name="Фильм",
            ),
        ),
    ]
