# Generated by Django 4.2.2 on 2023-07-12 17:14
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_raiting_rating"),
        ("movies", "0004_alter_review_movie"),
    ]

    operations = []
